### ISSUE TITLE
jinx padlock

### ISSUE THREAD

**Issue by fommil** [mitchellwrosen/ghc-switch#3]
Heh, seems we had similar ideas :smile:  https://gitlab.com/fommil/ghc-env

**Comment by hvr** [comment]
Indeed, `ghc-env` covers a similiar use-case.

ghc-switch's current approach seems a bit more in alignment for `cabal new-build` though: all ghcs installed via `ghc-switch` end up in a common `bin` folder as symlinks suffixed by version (i.e. `ghc-8.4.3`, `ghc-8.2.2` etc), this is the layout that works best with cabal's built-in tool lookup heuristic which follows symlinks to their targets to find associated tools; and then you can say e.g.

`cabal new-build -w ghc-8.4.3` or write

```
with-compiler: ghc-8.4.3
```

into your `cabal.project` file and things just work.

What I'm missing from ghc-switch is the ability to bootstrap from source in additional to providing installing from binary dists.

**Comment by fommil** [comment]
I'm happy to consolidate efforts! :smile: 

I'm starting as a Haskell developer in a month, so I'll definitely be looking to optimise my workflow at that point. I know the team I'm joining are using stack but they are also open to technical improvements and I **really** dislike that stack downloads binaries to my machine.

**Comment by hvr** [comment]
@fommil btw, you may also want to keep an eye on https://github.com/erikd/jenga which may soon become a general stack.yaml -> cabal.project converter

**Comment by fommil** [comment]
Cool! I'm really hoping I can have git source dependencies in cabal but I understand that's a work in progress. So useful to be able to pin to a repo / commit.

**Comment by hvr** [comment]
@fommil well, git source deps have landed for cabal-install-2.4 ... and 2.4 is going to be released shortly after GHC 8.6.1 final is released (probably within the next 4-5 weeks)

**Comment by mitchellwrosen** [comment]
@fommil I too am happy to consolidate efforts. At the moment the script _works-ish_ for me so it's not actively under development. Any feature requests or improvements are very welcome!

**Comment by fommil** [comment]
It looks like shims break a bunch of tools. So I'm going to revert to using cabal's ghc version management support, which I recently learnt about. I'll scrap my ghc-env and focus on automating compiling ghc.

**Comment by mitchellwrosen** [comment]
Please tell me more about cabal's ghc version management support! I too would prefer not to have such a poor script as this in my arsenal.

**Comment by fommil** [comment]
See hvr's comment above.
